### ISSUE TITLE
Using ReLUs for LSTM activation unconventional

### ISSUE THREAD

**Issue by mallamanis** [samialabed/method-name-prediction#2]
I see in [here](https://github.com/samialabed/method-name-prediction/blob/725d8c8b5df013b4fb403ebb6867883236a2a40f/notebooks/000-attention-network-exp.ipynb) that you have opted for LSTM layers that use ReLUs for activations. I think that this is an unconventional choice. If this model doesn't work well in the future, this would be a thing to revise.

**Comment by samialabed** [comment]
Thanks! 
I have removed that notebook as it was a leftover from when I was learning about attention. 
in the real model I am using GRU
