### ISSUE TITLE
Output of biLSTM seems odd

### ISSUE THREAD

**Issue by mallamanis** [samialabed/method-name-prediction#3]
I don't understand Keras quite well, but I suspect that something is off [here](https://github.com/samialabed/method-name-prediction/blob/725d8c8b5df013b4fb403ebb6867883236a2a40f/notebooks/000-attention-network-exp.ipynb). 

The output prediction (and thus the output layer) is a probability distribution over your output vocabulary elements (full method names for now). Instead, the code looks as if it predicts a single number (the output has a shape `batch_size x 1`) and you are using `binary_crossentropy` loss which seems to imply a binary classification problem.  Was this your intention?

**Comment by samialabed** [comment]
Thanks! Addressed in the new branch /attention
